config/routes.rb
Rails.application.routes.draw do

  resource :enrollments, only: [:create, :destroy]

  resource :sessions, only: [:new, :create, :destroy]

  resources :users
  
  resources :categories do 
  	resources :events, except: [:index]
  end
  
  resources :pages do 
  	collection { get 'about'}
  end
  
  root 'categories#index'
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <strong><%= pluralize object.errors.count, 'error' %> found:</strong>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <span class="muted">&copy; 2017 <%= mail_to 'test@example.com', 'Contact us' %></span>
    <p><%= link_to 'Twitter', 'https://twitter.com/bodrovis' %></p>
  </div>
</footer>

app/views/shared/_menu.html.erb
<% content_for :menu do %>
  <nav class="navbar navbar-inverse bg-inverse navbar-toggleable-md" id="main-menu">
    <button class="navbar-toggler navbar-toggler-right" type="button"
            data-toggle="collapse" data-target="#main-menu-collapse">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="icon-home"></i>
      BraveCoder
    <% end %>

    <div class="collapse navbar-collapse" id="main-menu-collapse">
      <ul class="navbar-nav mr-auto">
        <%= nav_item 'categories', categories_path, page %>
        <%= nav_item 'about', about_pages_path, page %>
      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="nav-link">Signed in as <strong><%= current_user.name %></strong></span>
          </li>
          <%= nav_item 'sign out', sessions_path, '', data: {method: :delete} %>
        <% else %>
          <%= nav_item 'register', new_user_path, page %>
          <%= nav_item 'sign in', new_sessions_path, page %>
        <% end %>
      </ul>
    </div>
  </nav>
<% end %>