config/routes.rb
Rails.application.routes.draw do

  resource :enrollments, only: [:create, :destroy]

  resource :sessions, only: [:new, :create, :destroy]

  resources :users
  
  resources :categories do 
  	resources :events, except: [:index]
  end
  
  resources :pages do 
  	collection { get 'about'}
  end
  
  root 'categories#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  starts_at   :datetime
#  ends_at     :datetime
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :integer
#
# Indexes
#
#  index_events_on_category_id  (category_id)
#  index_events_on_owner_id     (owner_id)
#

class Event < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User'

  has_many :enrollments
  has_many :users, through: :enrollments

  

  validates :title, presence: true, length: {minimum: 2},
  			 uniqueness: {scope: :category}
  			 
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  validate :ends_at_greater_than_starts_at

  after_create_commit -> { EventsMailer.notify_admins(self).deliver_now }

  def owned_by?(user)
    self.owner == user
  end

  def participant?(user)
    self.users.include? user
  end

  private

  def ends_at_greater_than_starts_at
    if self.starts_at.present? && self.ends_at.present? && self.starts_at > self.ends_at
      self.errors.add(:starts_at, 'should be earlier than the ending time')
      self.errors.add(:ends_at, 'should be later than the starting time')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_category!
  before_action :set_event!, only: [:show, :edit, :update, :destroy]
  before_action :check_owner!, only: [:edit, :update, :destroy]

  def edit
  end

  def update
    if @event.update_attributes(update_event_params)
      flash[:success] = "Event #{@event.title} updated!"
      redirect_to category_event_path(@category, @event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html do
        msg = @event.destroyed? ?
            {success: "Event #{@event.title} removed!"} :
            {danger: "Cannot remove #{@event.title} event..."}
        flash.merge! msg
        redirect_to category_path(@category)
      end
      format.js
    end
    if @event.destroy
      flash[:success] = "Event #{@event.title} removed!"
    else
      flash[:danger] = "Cannot remove #{@event.title} event..."
    end

  end

  def new
    @event = @category.events.build
  end

  def create
    @event = @category.events.build(create_event_params)
    if @event.save
      flash[:success] = "Event #{@event.title} was added to the #{@category.title}!"
      redirect_to category_event_path(@category, @event)
    else
      render :new
    end
  end

  def show
  end

  private

  def create_event_params
    params.require(:event).permit(:title, :description, :starts_at, :ends_at).merge(owner: current_user)
  end

  def update_event_params
    params.require(:event).permit(:title, :description, :starts_at, :ends_at)
  end

  def check_owner!
    unless @event.owned_by?(current_user)
      flash[:danger] = 'You are not permitted to perform this action!'
      redirect_back fallback_location: root_path
    end
  end

  def set_category!
    @category = Category.find(params[:category_id])
  end

  def set_event!
    @event = @category.events.find(params[:id])
  end
end

app/views/events/_event.html.erb
<div class="card mb-4" id="<%= dom_id event %>">
  <div class="card-block">
    <h4 class="card-title">
      <%= link_to event.title, category_event_path(event.category, event) %>
      <% if event.participant? current_user %>
        <span class="badge badge-info">enrolled</span>
      <% end %>
    </h4>
    <h6 class="card-subtitle mb-2 text-muted">Created by <%= event.owner.name %></h6>

    <p class="card-text lead"><%= event.description %></p>

    <dl>
      <dt>Starts at</dt>
      <dd><%= event.starts_at %></dd>

      <dt>Ends at</dt>
      <dd><%= event.ends_at %></dd>
    </dl>

    <% if event.owned_by? current_user %>
      <%= link_to 'Edit', edit_category_event_path(event.category, event), class: 'card-link btn btn-secondary btn-sm' %>
      <%= link_to 'Remove', category_event_path(event.category, event), class: 'card-link btn btn-danger btn-sm',
                  data: {method: :delete, confirm: 'Are you sure?', remote: true} %>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for [category, event] do |f| %>
  <%= render 'shared/errors', object: event %>

  <div class="form-group row">
    <div class="col-2">
      <%= f.label :title, class: 'col-form-label' %>
    </div>
    <div class="col-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-2">
      <%= f.label :description, class: 'col-form-label' %>
    </div>
    <div class="col-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-2">
      <%= f.label :starts_at, class: 'col-form-label' %>
    </div>
    <div class="col-10">
      <%= f.datetime_select :starts_at, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-2">
      <%= f.label :ends_at, class: 'col-form-label' %>
    </div>
    <div class="col-10">
      <%= f.datetime_select :ends_at, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-2 col-10">
      <%= f.submit 'Submit!', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/events/destroy.js.erb
<% if @event.destroyed? %>
$('#<%= dom_id @event %>').fadeOut();
<% else %>
alert("Cannot remove event <%= @event.title%>!");
<% end %>

app/views/events/edit.html.erb
<% title "Edit event at the #{@category.title}" %>
<% at_page %>

<%= render 'form', event: @event, category: @category %>

app/views/events/new.html.erb
<% title "Add event to the #{@category.title}" %>
<% at_page %>

<%= render 'form', event: @event, category: @category %>

app/views/events/show.html.erb
<% title @event.title %>
<% at_page %>

<% if @event.owned_by? current_user %>
  <div class="btn-group">
    <%= link_to 'Edit', edit_category_event_path(@category, @event), class: 'btn btn-primary' %>
    <%= link_to 'Remove', category_event_path(@category, @event), class: 'btn btn-danger',
                data: {method: :delete, confirm: 'Are you sure?', remote: true} %>
  </div>
<% end %>

<div class="card mt-4 mb-4">
  <div class="card-block">
    <p class="card-text"><%= @event.description %></p>

    <% if current_user.enrolled_for? @event %>
      <%= link_to 'Disenroll', enrollments_path(event_id: @event.id), class: 'btn btn-warning btn-lg mb-2',
                  data: {method: :delete} %>
    <% else %>
      <%= button_to 'Enroll', enrollments_path, class: 'btn btn-info btn-lg mb-2',
                    params: {event_id: @event.id} %>
    <% end %>
  </div>

  <div class="card-footer text-muted">
    <dl>
      <dt>Starts at</dt>
      <dd><%= @event.starts_at %></dd>

      <dt>Ends at</dt>
      <dd><%= @event.ends_at %></dd>

      <dt>Created by</dt>
      <dd><%= @event.owner.name %></dd>
    </dl>
  </div>
</div>

<%= link_to 'Back to category', category_path(@category), class: 'btn btn-secondary btn-sm' %>

<h2 class="mt-4">Enrolled users</h2>

<%= render @event.users %>