config/routes.rb
Rails.application.routes.draw do

  resource :enrollments, only: [:create, :destroy]

  resource :sessions, only: [:new, :create, :destroy]

  resources :users
  
  resources :categories do 
  	resources :events, except: [:index]
  end
  
  resources :pages do 
  	collection { get 'about'}
  end
  
  root 'categories#index'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#

class Category < ApplicationRecord
	has_many :events, dependent: :destroy

	validates :title, presence: true, length: {minimum: 2}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin!, except: [:show, :index]
  before_action :set_category!, only: [:edit, :update, :show, :destroy]


  def destroy
    @category.destroy
    respond_to do |format|
      format.js
    end
  end

  def show
    @events = @category.events.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = "Category #{@category.title} updated!"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def index
    @categories = Category.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category added!'
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:title, :description)
  end

  def set_category!
    @category = Category.find(params[:id])
  end
end

app/views/categories/_category.html.erb
<div class="card mb-4" id="<%= dom_id category %>">
  <div class="card-block">
    <h4 class="card-title"><%= link_to category.title, category_path(category) %></h4>
    <h6 class="card-subtitle mb-2 text-muted"><%= category.created_at %></h6>
    <p class="card-text"><%= category.description %></p>

    <% if current_user.admin? %>
      <%= link_to 'Edit', edit_category_path(category), class: 'card-link btn btn-secondary btn-sm' %>
      <%= link_to 'Remove', category_path(category), class: 'card-link btn btn-danger btn-sm',
                  data: {method: :delete, confirm: 'Are you sure?', remote: true} %>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_for category do |f| %>
  <%= render 'shared/errors', object: category %>

  <div class="form-group row">
    <div class="col-2">
      <%= f.label :title, class: 'col-form-label' %>
    </div>

    <div class="col-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-2">
      <%= f.label :description, class: 'col-form-label' %>
    </div>

    <div class="col-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-2 col-10">
      <%= f.submit 'Submit!', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/categories/destroy.js.erb
$('#<%= dom_id @category %>').fadeOut();

app/views/categories/edit.html.erb
<% title 'Edit category' %>
<% at_page('edit category') %>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<% title 'Categories' %>
<% at_page('categories') %>

<%= link_to 'Add category', new_category_path, class: 'btn btn-primary btn-lg mt-2 mb-4' %>

<%= render @categories %>

app/views/categories/new.html.erb
<% title 'Add Category' %>
<% at_page('add category') %>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<% title @category.title %>
<% at_page %>

<div class="btn-group">
  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary' %>
    <%= link_to 'Remove', category_path(@category), class: 'card-link btn btn-danger',
                data: {method: :delete, confirm: 'Are you sure?', remote: true} %>
  <% end %>
  <%= link_to 'Add Event Here', new_category_event_path(@category), class: 'btn btn-info' %>
</div>

<p class="lead mt-4"><%= @category.description %></p>

<h2>Events</h2>

<%= render @events %>